# feedback_builder.py — ML-based correction feedback, fully multilingual
#
# All text goes through voice_strings.t() — translations loaded from
# languages/translations_{lang}.json generated by generate_translations.py

from __future__ import annotations
import logging
import os
import random
from typing import Optional

import numpy as np
import config
from voice_strings import t, t_score, t_well_done, t_encouragement, t_correction, t_pose_intro, t_pose_step

logger = logging.getLogger(__name__)

# ── Model loading ──────────────────────────────────────────────────────────────
_MODEL_PATH = os.path.join(os.path.dirname(__file__), "model", "correction_ai.pkl")
_ml_model   = None
_ml_scaler  = None
_ml_bank    = {}
_ml_classes = None
_ML_AVAILABLE = False

def _load_model():
    global _ml_model, _ml_scaler, _ml_bank, _ml_classes, _ML_AVAILABLE
    if _ML_AVAILABLE:
        return True
    if not os.path.exists(_MODEL_PATH):
        logger.warning("correction_ai.pkl not found — using fallback templates")
        return False
    try:
        import joblib
        payload     = joblib.load(_MODEL_PATH)
        _ml_model   = payload["mlp"]
        _ml_scaler  = payload["scaler"]
        _ml_classes = _ml_model.classes_
        _ml_bank    = {c["id"]: c for c in payload["correction_bank"]}
        _ML_AVAILABLE = True
        logger.info(f"Correction AI loaded — {len(_ml_bank)} corrections")
        return True
    except Exception as e:
        logger.warning(f"Failed to load Correction AI: {e}")
        return False

_load_model()

# ── Feature encoding ───────────────────────────────────────────────────────────
_ALL_POSES = [
    "mountain","forward_fold","halfway_lift","warrior_i","warrior_ii",
    "warrior_iii","chair","tree","triangle","downward_dog","plank",
    "low_lunge","high_lunge","cobra","upward_dog","child",
    "seated_forward","cat_cow","unknown"
]
_ALL_JOINTS  = ["left_knee","right_knee","left_hip","right_hip",
                "left_shoulder","right_shoulder","left_elbow","right_elbow"]
_ALL_REGIONS = ["legs","hips","arms","core"]
_POSE_GROUPS = {
    "standing": ["mountain","tree","halfway_lift"],
    "warrior":  ["warrior_i","warrior_ii","warrior_iii"],
    "lunge":    ["low_lunge","high_lunge","chair"],
    "fold":     ["forward_fold","seated_forward","child"],
    "floor":    ["cobra","upward_dog","plank","cat_cow","downward_dog"],
    "triangle": ["triangle"],
}

def _pose_group(pose):
    for grp, members in _POSE_GROUPS.items():
        if pose in members: return grp
    return "standing"

def _severity_band(diff):
    if diff < 10: return 0
    if diff < 20: return 1
    if diff < 35: return 2
    return 3

def _encode(pose_name, primary_joint, direction, angle_diff, severity,
            bilateral, secondary_joint, score):
    feats = []
    pose_oh = [0.0]*len(_ALL_POSES)
    pi = _ALL_POSES.index(pose_name) if pose_name in _ALL_POSES else _ALL_POSES.index("unknown")
    pose_oh[pi] = 1.0; feats.extend(pose_oh)
    j_oh = [0.0]*(len(_ALL_JOINTS)+1)
    if primary_joint in _ALL_JOINTS: j_oh[_ALL_JOINTS.index(primary_joint)] = 1.0
    else: j_oh[-1] = 1.0
    feats.extend(j_oh)
    feats.append(1.0 if direction=="decrease" else 0.0)
    feats.append(min(angle_diff,90.0)/90.0)
    feats.append(severity/3.0)
    feats.append(1.0 if bilateral else 0.0)
    s_oh = [0.0]*(len(_ALL_JOINTS)+1)
    if bilateral and secondary_joint in _ALL_JOINTS:
        s_oh[_ALL_JOINTS.index(secondary_joint)] = 1.0
    else: s_oh[-1] = 1.0
    feats.extend(s_oh)
    feats.append(score/100.0)
    region = "legs"
    if primary_joint in ["left_hip","right_hip"]: region="hips"
    elif primary_joint in ["left_shoulder","right_shoulder","left_elbow","right_elbow"]: region="arms"
    r_oh=[0.0]*4; r_oh[_ALL_REGIONS.index(region)]=1.0; feats.extend(r_oh)
    db=[0.0,0.0,0.0,0.0]
    if angle_diff<10: db[0]=1.0
    elif angle_diff<20: db[1]=1.0
    elif angle_diff<35: db[2]=1.0
    else: db[3]=1.0
    feats.extend(db)
    feats.append(1.0 if 70<=score<=82 else 0.0)
    groups=list(_POSE_GROUPS.keys())
    grp=_pose_group(pose_name)
    g_oh=[0.0]*len(groups)
    if grp in groups: g_oh[groups.index(grp)]=1.0
    feats.extend(g_oh)
    return np.array(feats, dtype=np.float32)

def _ml_predict(pose_name, joint, direction, diff, score, bilateral=False, secondary_joint=""):
    if not _ML_AVAILABLE: return "", 0, 0.0
    try:
        sev   = _severity_band(diff)
        feat  = _encode(pose_name,joint,direction,diff,sev,bilateral,secondary_joint,score).reshape(1,-1)
        probs = _ml_model.predict_proba(_ml_scaler.transform(feat))[0]
        idx   = int(np.argmax(probs))
        cid   = _ml_classes[idx]
        conf  = float(probs[idx])
        english = _ml_bank.get(cid, {}).get("text", "")
        # Translate the correction text
        text = t_correction(cid, english)
        return text, cid, conf
    except Exception as e:
        logger.debug(f"ML predict error: {e}")
        return "", -1, 0.0

# ── Fallback templates (translated) ───────────────────────────────────────────
_FALLBACK: dict = {
    "left_knee":      {"decrease": "correction_0",  "increase": "correction_9"},
    "right_knee":     {"decrease": "correction_15", "increase": "correction_21"},
    "left_hip":       {"increase": "correction_31", "decrease": "correction_36"},
    "right_hip":      {"increase": "correction_40", "decrease": "correction_43"},
    "left_shoulder":  {"increase": "correction_49", "decrease": "correction_55"},
    "right_shoulder": {"increase": "correction_59", "decrease": "correction_63"},
    "left_elbow":     {"increase": "correction_71", "decrease": "correction_75"},
    "right_elbow":    {"increase": "correction_78", "decrease": "correction_81"},
}

# ── Public API ─────────────────────────────────────────────────────────────────

def build_correction_message(
    comparison: dict,
    pose_name: str = "",
    max_corrections: int = 2,
    overall_score: float = 70.0,
) -> Optional[str]:
    misaligned = [
        (j, info) for j, info in comparison.items()
        if info.get("misaligned") and info.get("direction") and info.get("diff") is not None
    ]
    if not misaligned:
        return None

    misaligned.sort(key=lambda x: x[1]["diff"], reverse=True)
    top = misaligned[:max_corrections]
    avg_diff = sum(i["diff"] for _, i in top) / len(top)

    best_text = ""
    best_conf = -1.0

    if _ML_AVAILABLE:
        # Bilateral attempt
        if len(top) >= 2:
            j1, i1 = top[0]; j2, i2 = top[1]
            if i1["direction"] == i2["direction"]:
                text, _, conf = _ml_predict(pose_name, j1, i1["direction"],
                    (i1["diff"]+i2["diff"])/2, overall_score, bilateral=True, secondary_joint=j2)
                if conf > best_conf and text:
                    best_conf, best_text = conf, text

        for joint, info in top:
            text, _, conf = _ml_predict(pose_name, joint, info["direction"],
                info["diff"], overall_score)
            if conf > best_conf and text:
                best_conf, best_text = conf, text

    if not best_text:
        # Fallback: use pre-translated correction strings
        parts = []
        for joint, info in top:
            key = _FALLBACK.get(joint, {}).get(info["direction"])
            if key:
                cid = int(key.split("_")[1])
                english = _ml_bank.get(cid, {}).get("text", "")
                parts.append(t_correction(cid, english) if english else key)
            else:
                friendly = config.JOINT_FRIENDLY_NAMES.get(joint, joint.replace("_"," "))
                verb = "open" if info["direction"]=="increase" else "close"
                parts.append(f"{verb.capitalize()} your {friendly} a little.")
        if not parts:
            return None
        best_text = " ".join(parts)

    enc = t_encouragement(avg_diff)
    return (best_text + " " + enc).strip() if enc else best_text


def build_score_message(score: float, label: str) -> str:
    return t_score(score, label)


def build_well_done_message() -> str:
    return t_well_done()


def build_step_message(pose_name: str, step: str, step_num: int, total: int,
                       pose_key: str = "", step_index: int = 0) -> str:
    # Translate the step text if we have the key
    if pose_key and step_index >= 0:
        step = t_pose_step(pose_key, step_index, step)

    intros = [
        t("step_prefix_numbered", n=step_num, total=total),
        t("step_prefix_next"),
        t("step_prefix_now"),
        "",
    ]
    intro = random.choice(intros)
    return f"{intro} {step}".strip()


def build_pose_intro(pose_name: str, sanskrit: str, description: str,
                     pose_key: str = "") -> str:
    from voice_strings import _load, _strings, t
    _load()
    if pose_key:
        desc = _strings.get(f"desc_{pose_key}") or description
        p_name = t(f"pose_{pose_key}")
    else:
        desc = description
        p_name = pose_name
    return t_pose_intro(pose_key or pose_name, p_name, sanskrit, desc)
